#include "simple_matrix.h"  //Import the library

/*
 * This is where you can copy and paste the array generated by the python software 
 */
uint8_t TEST_BITMAP[] = {
};

/*
 * Initialize the library. The 4 means that the CS pin is connected to pin D4.
 * You can change this to whatever you want, just make sure to connect the CS
 * pin to the pin number.
 * The disp means that any future function calls to the library uses "disp" as the
 * library's object name. For example, the library has a function called
 * "setIntensity", you need to write "disp.setIntensity" to call that function.
 */
simpleMatrix disp(4);

// This code will run only once when the Arduino is turned on.
void setup(){
  // Starts the library
  disp.begin();
  // Set the LED's intensity. This value can be anywhere between 0 and 15.
  disp.setIntensity(0x02);
  // Send the custom bitmap to the first matrix
  disp.sendCustomSymbol(0, TEST_BITMAP); 
}

// After void setup(), this code will run and loop forever.
void loop(){
}
